reset test.yaml to original version

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,38 +1,35 @@
 name: CI
-on: [workflow_dispatch, pull_request, push]
+on:
+  workflow_dispatch:
+  pull_request:
+  push:
+    branches: [main]
 
 jobs:
   test:
-    runs-on: ubuntu-latest
-    env:
-      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Use secret in the environment
-      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
-      RIZA_API_KEY: ${{ secrets.RIZA_API_KEY }}
+    strategy:
+      fail-fast: true
+      matrix:
+        os:  [ubuntu, macos]
+        version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
+    runs-on: ${{ matrix.os }}-latest
     steps:
-      - name: Check out repository (clean clone)
-        uses: actions/checkout@v4
+      - uses: fastai/workflows/nbdev-ci@master
         with:
-          fetch-depth: 0
-
-      - name: Set up Python 3.12
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.12.6'
-
-      - name: Install dependencies
+          version: ${{ matrix.version }}
+          pre: 1
+      - name: test docs build
+        if: ${{ (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') && matrix.version == '3.10' && matrix.os == 'ubuntu' }}
         run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt  # Ensure all required dependencies are installed
-          pip install -e '.[dev]'  # Install development dependencies
-
-      - name: Verify dependency installation
-        run: |
-          python -c "import nbdev; print('nbdev installed')"
-          python -c "import langgraph; print('langgraph installed')"
-          python -c "import datasets; print('datasets installed')"
-
-      - name: Run nbdev commands
-        run: |
-          nbdev_install_hooks
-          nbdev_export
-          nbdev_test
+          set -ux
+          wget -q $(curl https://latest.fast.ai/pre/quarto-dev/quarto-cli/linux-amd64.deb)
+          sudo dpkg -i quarto*.deb
+          nbdev_docs
+          if [ -f "_docs/index.html" ]; then
+            echo "docs built successfully."
+          else
+            echo "index page not found in rendered docs."
+            ls -la
+            ls -la _docs
+            exit 1
+          fi
